Update kali

diff --git a/kali_nethunter/kali b/kali_nethunter/kali
--- a/kali_nethunter/kali
+++ b/kali_nethunter/kali
@@ -1,62 +1,68 @@
-#!/data/data/com.termux/files/usr/bin/bash -e
+#!/bin/bash
 
-cd ${HOME}
-
-## termux-exec sets LD_PRELOAD so let's unset it before continuing
-unset LD_PRELOAD
-
-## Workaround for Libreoffice, also needs to bind a fake /proc/version
-if [ ! -f kali-arm64/root/.version ]; then
-    touch kali-arm64/root/.version
-fi
-
-## Default user is "kali"
-user="kali"
-home="/home/$user"
-start="sudo -u kali /bin/bash"
-
-## NH can be launched as root with the "-r" cmd attribute
-## Also check if user kali exists, if not start as root
-if grep -q "kali" kali-arm64/etc/passwd; then
-    KALIUSR="1";
-else
-    KALIUSR="0";
-fi
-if [[ $KALIUSR == "0" || ("$#" != "0" && ("$1" == "-r" || "$1" == "-R")) ]];then
-    user="root"
-    home="/$user"
-    start="/bin/bash --login"
-    if [[ "$#" != "0" && ("$1" == "-r" || "$1" == "-R") ]];then
-        shift
+function start-kex() {
+    if [ ! -f ~/.vnc/passwd ]; then
+        passwd-kex
     fi
-fi
+    USR=$(whoami)
+    if [ $USR == "root" ]; then
+        SCREEN=":2"
+    else
+        SCREEN=":1"
+    fi
+    export MOZ_FAKE_NO_SANDBOX=1; export HOME=${HOME}; export USER=${USR}; LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver $SCREEN >/dev/null 2>&1 </dev/null
+    starting_kex=1
+    return 0
+}
 
-cmdline="proot \
-        --link2symlink \
-        -0 \
-        -L \
-        --ashmem-memfd \
-        -k 6.11.2-1kali1 \
-        -r kali-arm64 \
-        -b /dev \
-        -b /proc \
-        -b /sys \
-        -b /sdcard \
-        -b kali-arm64:/dev/shm \
-        -w /root \
-        -w $home \
-           /usr/bin/env -i \
-           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \
-           HOME=$home \
-           HOME=/root \
-           TMP=/tmp \
-           TERM=$TERM \
-           LANG=C.UTF-8 \
-           $start"
+function stop-kex() {
+    vncserver -kill :1 | sed s/"Xtigervnc"/"NetHunter KeX"/
+    vncserver -kill :2 | sed s/"Xtigervnc"/"NetHunter KeX"/
+    return 0
+}
 
-cmd="$@"
-if [ "$#" == "0" ];then
-    exec $cmdline
-else
-    $cmdline -c "$cmd"
-fi
+function passwd-kex() {
+    vncpasswd
+    return 0
+}
+
+function status-kex() {
+    sessions=$(vncserver -list | sed s/"TigerVNC"/"NetHunter KeX"/)
+    if [[ $sessions == *"590"* ]]; then
+        printf "\n${sessions}\n"
+        printf "\nYou can use the KeX client to connect to any of these displays.\n\n"
+    else
+        if [ ! -z $starting_kex ]; then
+            printf '\nError starting the KeX server.\nPlease try "nethunter kex kill" or restart your termux session and try again.\n\n'
+        fi
+    fi
+    return 0
+}
+
+function kill-kex() {
+    pkill Xtigervnc
+    return $?
+}
+
+case $1 in
+    start)
+        start-kex
+        ;;
+    stop)
+        stop-kex
+        ;;
+    status)
+        status-kex
+        ;;
+    passwd)
+        passwd-kex
+        ;;
+    kill)
+        kill-kex
+        ;;
+    *)
+        stop-kex
+        start-kex
+        status-kex
+        ;;
+esac
